version: '2'
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    expose:
      - "3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - '4406:3306'
    restart: always
  web:
    image: drupal:7-apache
    ports:
      - 8080:80
    restart: always
    links:
      - db
